name: learn
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.9.2


dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  permission_handler: ^12.0.1
  flutter_background_service: ^5.1.0
  flutter_local_notifications: ^19.4.2
  wakelock_plus: ^1.4.0
  shared_preferences: ^2.5.3
  device_info_plus: ^12.1.0
  path_provider: ^2.1.5

dev_dependencies:
  flutter_test:
    sdk: flutter

  
  flutter_lints: ^5.0.0

flutter:

  uses-material-design: true

